### ISSUE TITLE
请问在实际项目中，翻页请求附近问题

### ISSUE THREAD

**Issue by Ryan-Miao** [wenhao/geohash#3]
第一次请求附近1km以内的，随着翻页精度改变，比如2km。但2km的结果包含1km。难道每次都要排除一次1km的数据吗

**Comment by wenhao** [comment]
这个是没办法的，必须使用距离公式排除。但话又说回来，1km, 2km, 甚至5km搜索出来的候选者都是非常少的，就算几百上千的使用距离公式过滤也是非常快的。
